### PR TITLE
582 bug no log information is provided for failing api check setup scripts 2

### LINKED ISSUE #581: bug: check titles aren't printed when using `--verbose`
### Node.js version

v16.17.0

### NPM version

v8.15.0

### @checkly/cli version

0.4.7

### Steps to reproduce

Create a boilerplate project using `npm create @checkly/cli`. Then run the tests with `npx checkly test --verbose`.

### What is expected?

The names/titles of the checks should be printed. This would make it possible to differentiate which logs come from which checks.

### What is actually happening?

The names/titles are not printed. It isn't possible to tell which logs come from which checks.

```
$ npx checkly test --verbose

Running 2 checks in eu-west-1.


    ──HTTP Response───────────────────────────────────────────────────────────────────
    Status Code: 200 OK
    Headers:
      server: Cowboy
      connection: close
      content-type: application/json; charset=utf-8
      vary: origin
      access-control-expose-headers: WWW-Authenticate,Server-Authorization,x-signed-dashboard,content-range
      strict-transport-security: max-age=15768000; includeSubDomains; preload
      x-frame-options: DENY
      x-xss-protection: 1; mode=block
      x-download-options: noopen
      x-content-type-options: nosniff
      cache-control: no-cache
      content-length: 62
      accept-ranges: bytes
      date: Tue, 14 Mar 2023 14:52:55 GMT
      via: 1.1 vegur
    Body:
      {"apiCheckResults":4627927602,"browserCheckResults":606320313}

    ──Assertions──────────────────────────────────────────────────────────────────────
    ✔ status code equals target "200".
    ✔ JSON body property "$.apiCheckResults" is greater than target "0".


    ──Logs────────────────────────────────────────────────────────────────────────────
    DEBUG, 3:52:53 PM, Starting job
    DEBUG, 3:52:53 PM, Backend used : Lambda
    DEBUG, 3:52:53 PM, Compiling environment variables
    DEBUG, 3:52:53 PM, Creating runtime using version 2022.10
    DEBUG, 3:52:53 PM, Running Playwright test script
    INFO, 3:52:54 PM, Running 1 test using 1 worker
    INFO, 3:52:54 PM,
    INFO, 3:52:55 PM, [1/1] [chromium] › ../../var/task/src/2022-10/node_modules/vm2/lib/bridge.js:479:11 › Checkly Homepage
    INFO, 3:53:00 PM,
    INFO, 3:53:00 PM,
    INFO, 3:53:00 PM, 1 passed (6s)
    DEBUG, 3:53:00 PM, Run finished
    DEBUG, 3:53:00 PM, Uploading log file

__checks__/api.check.ts
  ✔ Homepage - fetch stats (39ms)
__checks__/homepage.spec.ts
  ✔ homepage.spec.ts (7s)

2 passed, 2 total
```

### Any additional comments?

_No response_

### LINKED ISSUE #582: bug: no log information is provided for failing API check setup scripts
### Node.js version

v16.17.0

### NPM version

v8.15.0

### @checkly/cli version

v0.4.7

### Steps to reproduce

Create an API check with a failing setup script. Run with `npx checkly test`.

```
// api_check.check.ts
import { ApiCheck, AssertionBuilder } from '@checkly/cli/constructs'

new ApiCheck('homepage-api-check-1', {
  name: 'Homepage - fetch stats',
  alertChannels: [],
  degradedResponseTime: 10000,
  maxResponseTime: 20000,
  localSetupScript: 'throw new Error("it doesnt work")',
  request: {
    url: 'https://api.checklyhq.com/public-stats',
    method: 'GET',
    followRedirects: true,
    skipSsl: false,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.apiCheckResults').greaterThan(0),
    ],
  }
})
```

### What is expected?

The CLI should print clear logs from the failing setup script.

### What is actually happening?

```
$ npx checkly test

Running 1 checks in eu-west-1.

✖ Homepage - fetch stats (0ms)



__checks__/api.check.ts
  ✖ Homepage - fetch stats (0ms)

1 failed, 1 total
```

### Any additional comments?

The CLI also doesn't print setup/teardown script logs when the API check is passing and we run the check with `npx checkly test --verbose`.

### PR DESCRIPTION
**Pull request by tnolet**
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a04dc1a112f0e26b2f2d3f)

## Affected Components
* [x] CLI
* [ ] Create CLI
* [x] Test
* [ ] Docs
* [ ] Examples
* [ ] Other

## Notes for the Reviewer
- prints HTTP request on verbose and/or error
- prints API check log on verbose and/or error
- print name of check on verbose
- fine tunes the log output formatting 👇

- timestamps first with 24h clock instead of AM/PM
- align log level statements
CleanShot 2023-03-24 at 10 48 06

- adds tests for core formatting functions

> Resolves #582 
> Resolves #581

### CODE REVIEW

File: packages/cli/src/reporters/util.ts [hunk 1]
```diff
@@ -161,7 +195,7 @@ function formatHttpResponse (response: any) {
 
 function formatLogs (logs: Array<{ level: string, msg: string, time: number }>) {
   return logs.flatMap(({ level, msg, time }) => {
-    const timestamp = DateTime.fromMillis(time).toLocaleString(DateTime.TIME_WITH_SECONDS)
+    const timestamp = DateTime.fromMillis(time).toLocaleString(DateTime.TIME_24_WITH_SECONDS)
```
Comment (umutuzgur) [inline packages/cli/src/reporters/util.ts:198]: I see no mention of these changes in the PR description, could you add it there as well?

Comment (tnolet) [reply packages/cli/src/reporters/util.ts:198]: fixed
